Import

In [1]:
import pandas as pd

Reading Files

In [2]:
essays = pd.read_csv('kdd-cup-2014-predicting-excitement-at-donors-choose/data/essays.csv')
outcomes = pd.read_csv('kdd-cup-2014-predicting-excitement-at-donors-choose/data/outcomes.csv')
projects = pd.read_csv('kdd-cup-2014-predicting-excitement-at-donors-choose/data/projects.csv')
donations = pd.read_csv('kdd-cup-2014-predicting-excitement-at-donors-choose/data/donations.csv')

Merging

In [3]:
combined = projects.merge(outcomes,how='inner',on='projectid').merge(essays,how='inner',on='projectid')

In [4]:
combined.isna().sum()

projectid                                              0
teacher_acctid_x                                       0
schoolid                                               0
school_ncesid                                      38848
school_latitude                                        0
school_longitude                                       0
school_city                                            0
school_state                                           0
school_zip                                             4
school_metro                                       75488
school_district                                      922
school_county                                         17
school_charter                                         0
school_magnet                                          0
school_year_round                                      0
school_nlns                                            0
school_kipp                                            0
school_charter_ready_promise                           0
teacher_prefix                                         0
teacher_teach_for_america                              0
teacher_ny_teaching_fellow                             0
primary_focus_subject                                 36
primary_focus_area                                    36
secondary_focus_subject                           193949
secondary_focus_area                              193949
resource_type                                         43
poverty_level                                          0
grade_level                                            7
fulfillment_labor_materials                        35082
total_price_excluding_optional_support                 0
total_price_including_optional_support                 0
students_reached                                     144
eligible_double_your_impact_match                      0
eligible_almost_home_match                             0
date_posted                                            0
is_exciting                                            0
at_least_1_teacher_referred_donor                  94398
fully_funded                                           0
at_least_1_green_donation                          94398
great_chat                                             0
three_or_more_non_teacher_referred_donors          94398
one_non_teacher_referred_donor_giving_100_plus     94398
donation_from_thoughtful_donor                     94398
great_messages_proportion                         179839
teacher_referred_count                             94398
non_teacher_referred_count                         94398
teacher_acctid_y                                       0
title                                                 17
short_description                                    132
need_statement                                      1472
essay                                                  3
dtype: int64

Preparing the Data

In [5]:
#dropping columns that are not important such as teacher account id
#dropping columns with too many categories such as school city

columns = ['projectid','school_state','school_metro','school_magnet','school_nlns',
           'school_kipp','school_charter_ready_promise','teacher_teach_for_america',
           'teacher_ny_teaching_fellow','primary_focus_subject','primary_focus_area',
           'resource_type','poverty_level','grade_level','total_price_excluding_optional_support',
           'total_price_including_optional_support','students_reached','eligible_double_your_impact_match',
           'eligible_almost_home_match','date_posted','fully_funded','short_description','need_statement','essay']

data = combined[columns]

In [6]:
#convert t/f values to binary for relevant categorical data

columns_binary = ['school_magnet','school_nlns',
           'school_kipp','school_charter_ready_promise','teacher_teach_for_america',
           'teacher_ny_teaching_fellow','eligible_double_your_impact_match',
           'eligible_almost_home_match','fully_funded']

binary_map = {'f':0,'t':1}

for col in columns_binary:
    data.loc[:,col] = data[col].map(binary_map)

data

,projectid,school_state,school_metro,school_magnet,school_nlns,school_kipp,school_charter_ready_promise,teacher_teach_for_america,teacher_ny_teaching_fellow,primary_focus_subject,...,total_price_excluding_optional_support,total_price_including_optional_support,students_reached,eligible_double_your_impact_match,eligible_almost_home_match,date_posted,fully_funded,short_description,need_statement,essay
0,62526d85d2a1818432d03d600969e99c,IL,suburban,0,0,0,0,0,0,Special Needs,...,444.36,522.78,7.0,0,0,2013-12-31,1,"If they can't learn the way we teach, we teach...","My students need puzzles, games and visual lea...","If they can't learn the way we teach, we teach..."
1,33d59ac771b80222ad63ef0f4ac47ade,ID,urban,0,0,0,0,0,0,Mathematics,...,233.24,274.40,30.0,0,0,2013-12-31,0,"Which is bigger, three liters or three quarts?...",My students need capacity tools and resources ...,"Which is bigger, three liters or three quarts?..."
2,1a3aaeffc56dd2a421e37d8298024c0a,NH,suburban,0,0,0,0,0,0,Environmental Science,...,285.09,335.40,230.0,0,0,2013-12-31,0,Do you remember classrooms that used just book...,My students need UV sensitive beads and a Vern...,Do you remember classrooms that used just book...
3,33aa19ee4da4c5adf47d0dfb84fab5ef,VA,urban,0,0,0,0,0,0,Literacy,...,232.94,274.05,18.0,0,0,2013-12-31,0,My class was given the beautiful gift of books...,My students need labels and book bins to organ...,My class was given the beautiful gift of books...
4,e31c0ea8b68f404699dfb0d39e9bc99b,IL,urban,1,0,0,0,0,0,Environmental Science,...,513.41,604.01,70.0,1,0,2013-12-31,1,Thinking back in school science was either rea...,My students need an Interactive whiteboard les...,Thinking back in school science was either rea...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619321,a7236ea96c812895cafc5d700d779147,NY,urban,0,0,0,0,0,0,Environmental Science,...,231.00,281.71,0.0,0,0,2002-09-17,1,My name is Mary Reide. I am a New York City T...,"The cost of this proposal is [price], includin...",My name is Mary Reide. I am a New York City T...
619322,e02da37beb332eb66c2d2ba989c597ad,NY,urban,0,0,0,0,0,0,Economics,...,1129.00,1376.83,0.0,0,0,2002-09-17,1,I teach economics to 25 students at Satellite ...,"The cost of this proposal is $1377, including ...",I teach economics to 25 students at Satellite ...
619323,82e536f14eadf2671a70e03416f695a3,NY,urban,1,0,0,0,0,0,Early Development,...,125.00,152.44,0.0,0,0,2002-09-16,1,I just returned from 3 weeks in S. Africa. I w...,"The cost of this proposal is [price], includin...",I just returned from 3 weeks in S. Africa. I ...
619324,e139df754a873a62d93daa56acbf8040,NY,NaN,0,0,0,0,0,0,Literacy,...,125.00,152.44,0.0,0,0,2002-09-13,1,I teach 9th grade Humanities at Vanguard High ...,"The cost of this proposal is [price], includin...",I teach 9th grade Humanities at Vanguard High ...
619325,77558a6eda151deee9a00553f7fccfc7,NY,urban,1,0,0,0,0,0,Other,...,229.00,279.27,0.0,0,0,2002-09-13,1,I am a first year teacher assigned to the 6th ...,"The cost of this proposal is [price], includin...",I am a first year teacher assigned to the 6th ...

In [7]:
#dropping outliers

data = data.sort_values(by='total_price_excluding_optional_support')

data = data[data['total_price_excluding_optional_support'] != 0.00]
data = data[:-2]

data

,projectid,school_state,school_metro,school_magnet,school_nlns,school_kipp,school_charter_ready_promise,teacher_teach_for_america,teacher_ny_teaching_fellow,primary_focus_subject,...,total_price_excluding_optional_support,total_price_including_optional_support,students_reached,eligible_double_your_impact_match,eligible_almost_home_match,date_posted,fully_funded,short_description,need_statement,essay
618921,2a4f36945cda7d32cc40692c16ce8d1d,NY,urban,0,0,0,0,0,0,Literature & Writing,...,9.00,10.98,0.0,0,0,2002-11-11,1,"I teach 12th-grade literature in the Bronx, at...","The cost of this proposal is $11, including sh...","I teach 12th-grade literature in the Bronx, at..."
618350,93194de2e53cd7b9d3294b4c9b419a5d,NY,urban,1,0,0,0,0,0,Other,...,9.00,10.98,0.0,0,0,2003-06-17,1,I am currently a kindergarten teacher in a col...,NaN,I am currently a kindergarten teacher in a col...
619266,11646fe7b97e08354cde2246c5e582c1,NY,urban,0,0,0,0,0,1,Visual Arts,...,9.00,10.98,0.0,0,0,2002-09-19,1,NaN,"The cost of this proposal is [price], includin...",This is a District 10 school in a low income a...
619198,647feca31c2ecaa8c605523bbc334ebd,NY,urban,1,0,0,0,0,0,Other,...,9.00,10.98,0.0,0,0,2002-09-19,1,I am a first year teacher assigned to the 6th ...,"The cost of this proposal is $11, including sh...",I am a first year teacher assigned to the 6th ...
447154,b88e7c3fc0f52d930bd95cb2f812fa1d,NY,urban,0,0,0,0,0,1,History & Geography,...,9.00,10.98,50.0,1,0,2009-11-13,1,Groups of students will research each one of t...,My students need funding for our entire class ...,A pivotal moment in 50 students' education cam...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103842,b13aaa06baad031277fdd7c7f7370c02,HI,NaN,0,0,0,0,0,0,Health & Wellness,...,94857.17,111596.67,110.0,0,0,2013-04-16,1,Need a break to stimulate? After several hours...,My students need a safe and multi-functional p...,Need a break to stimulate? After several hours...
442703,ba33798533580b2d3167c455ba101a63,CA,suburban,0,0,0,0,0,0,Literature & Writing,...,97974.78,119481.44,200.0,1,0,2009-12-13,0,\r\nIf two hundred and fifty HP Mini 110 1020N...,My students need 250 HP Mini Atom laptops comp...,I teach high school English Second Language (E...
81345,dc106a943920d1fbe1f4f079c212c732,OK,suburban,0,0,0,0,0,0,Literacy,...,139725.41,164382.84,440.0,0,0,2013-07-26,1,"On May 20, a powerful tornado destroyed Plaza ...",My students need (30) Promethean interactive w...,"On May 20, a powerful tornado destroyed Plaza ..."
81464,5b9ec0ec98a6ef660892cca50e3d9f2c,OK,urban,0,0,0,0,0,0,Literacy,...,139725.41,164382.84,650.0,0,0,2013-07-26,1,"On May 20, a powerful tornado destroyed Plaza ...",My students need (30) Promethean interactive w...,"On May 20, a powerful tornado destroyed Briarw..."
579163,d6ef27c07c30c81f0c16c32b6acfa2ff,TX,suburban,0,0,0,0,0,0,Mathematics,...,437212.00,533185.37,1100.0,0,0,2007-02-23,0,As the Testing Coordinator and Math Teacher at...,The cost of 420 Toshiba Tecra computers is [pr...,As the Testing Coordinator and Math Teacher at...

In [8]:
#sort ascending chronologically

data = data.sort_values(by='date_posted')

#drop missing value

percent_loss = round((data.shape[0] - data.dropna().shape[0])/data.shape[0],4)

print(f'{percent_loss*100}%')

12.41%

In [9]:
data.dropna(inplace=True)
data

,projectid,school_state,school_metro,school_magnet,school_nlns,school_kipp,school_charter_ready_promise,teacher_teach_for_america,teacher_ny_teaching_fellow,primary_focus_subject,...,total_price_excluding_optional_support,total_price_including_optional_support,students_reached,eligible_double_your_impact_match,eligible_almost_home_match,date_posted,fully_funded,short_description,need_statement,essay
619325,77558a6eda151deee9a00553f7fccfc7,NY,urban,1,0,0,0,0,0,Other,...,229.00,279.27,0.0,0,0,2002-09-13,1,I am a first year teacher assigned to the 6th ...,"The cost of this proposal is [price], includin...",I am a first year teacher assigned to the 6th ...
619323,82e536f14eadf2671a70e03416f695a3,NY,urban,1,0,0,0,0,0,Early Development,...,125.00,152.44,0.0,0,0,2002-09-16,1,I just returned from 3 weeks in S. Africa. I w...,"The cost of this proposal is [price], includin...",I just returned from 3 weeks in S. Africa. I ...
619312,b7303e499d731d3ed5d005bc036be47b,NY,urban,0,0,0,0,0,0,Literacy,...,146.00,178.05,0.0,0,0,2002-09-17,1,Hello! I am a fifth and sixth grade bilingual ...,"The cost of this proposal is [price], includin...",Hello! I am a fifth and sixth grade bilingual ...
619300,80c5eaac88db21c471c74de52aee0973,NY,urban,0,0,0,0,0,0,Literature & Writing,...,705.00,859.76,0.0,0,0,2002-09-17,1,The 3 novels that I am requesting are absolute...,"The cost of this proposal is $860, including s...",The 3 novels that I am requesting are absolute...
619322,e02da37beb332eb66c2d2ba989c597ad,NY,urban,0,0,0,0,0,0,Economics,...,1129.00,1376.83,0.0,0,0,2002-09-17,1,I teach economics to 25 students at Satellite ...,"The cost of this proposal is $1377, including ...",I teach economics to 25 students at Satellite ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,83b2f7f7acdd941ea7ce06718ad88cb0,IL,urban,0,0,0,0,0,0,Health & Wellness,...,343.18,403.74,150.0,0,0,2013-12-31,1,I have entered high school with the wrong hair...,My students need 40 copies of the book Speak t...,I have entered high school with the wrong hair...
152,d099bd2b6b0a47e75fa2717f4fad4e94,FL,suburban,0,0,0,0,0,0,Gym & Fitness,...,334.43,393.45,400.0,1,0,2013-12-31,1,They call me the painter of dancers. They don'...,My students need colored construction paper fo...,They call me the painter of dancers. They don'...
7,0ff5dec32bf793243a8b0b2c023a81f0,FL,rural,0,0,0,0,0,0,Literacy,...,809.32,952.14,17.0,0,0,2013-12-31,1,Technology is a major part of educating studen...,My students need 2 computers for our classroom...,Technology is a major part of educating studen...
54,8c7353b1ca1486c156f251c4dc915353,IN,urban,0,0,0,0,0,0,Gym & Fitness,...,1994.56,2346.54,350.0,0,0,2013-12-31,0,Typical day in Gym class doesn't involve a lot...,My students need strapless heart rate monitors...,Typical day in Gym class doesn't involve a lot...
117,a78bb755d61652b8498d9d9a1e8eadd4,VA,urban,0,0,0,0,0,0,Literacy,...,177.21,208.48,20.0,1,0,2013-12-31,1,A typical day in the classroom is students who...,My students need items to help them learn thei...,A typical day in the classroom is students who...